package top.vlor.test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @Descreption:
 * @Author: vlor
 * @Date: Created in 11:30 2018/7/2
 * @Modified by：
 */
public class CountryTest {
    public static void main(String[] args) {
        Map<String, String> map = new HashMap();

        map.put("AF", "阿富汗");
        map.put("AX", "奥兰群岛");
        map.put("AL", "阿尔巴尼亚");
        map.put("DZ", "阿尔及利亚");
        map.put("AS", "美属萨摩亚");
        map.put("WS", "萨摩亚、东部");
        map.put("WS", "萨摩亚,西方");
        map.put("AD", "安道尔");
        map.put("AO", "安哥拉");
        map.put("AI", "安圭拉");
        map.put("AG", "安提瓜岛和巴布达");
        map.put("AR", "阿根廷");
        map.put("AM", "亚美尼亚");
        map.put("AW", "阿鲁巴");
        map.put("AU", "澳大利亚");
        map.put("AT", "奥地利");
        map.put("AZ", "阿塞拜疆");
        map.put("BD", "孟加拉国");
        map.put("BH", "巴林");
        map.put("BS", "巴哈马群岛");
        map.put("BB", "巴巴多斯");
        map.put("BY", "白俄罗斯");
        map.put("BE", "比利时");
        map.put("BZ", "伯利兹");
        map.put("BJ", "贝宁");
        map.put("BM", "百慕大群岛是");
        map.put("BT", "不丹");
        map.put("BO", "玻利维亚");
        map.put("BA", "波黑");
        map.put("BW", "博茨瓦纳");
        map.put("BV", "布维岛");
        map.put("BR", "巴西");
        map.put("BN", "文莱");
        map.put("BG", "保加利亚");
        map.put("BF", "布基纳法索");
        map.put("BI", "布隆迪");
        map.put("KH", "柬埔寨");
        map.put("CM", "喀麦隆");
        map.put("CA", "加拿大");
        map.put("CV", "佛得角");
        map.put("CF", "中非");
        map.put("TD", "乍得");
        map.put("CL", "智利");
        map.put("CX", "圣诞岛");
        map.put("CC", "科科斯（基林）群岛");
        map.put("CO", "哥伦比亚");
        map.put("KM", "科摩罗");
        map.put("CD", "刚果(金)");
        map.put("CG", "刚果");
        map.put("CK", "库克是");
        map.put("CR", "哥斯达黎加");
        map.put("CI", "象牙海岸");
        map.put("CN", "中国");
        map.put("HR", "克罗地亚");
        map.put("CU", "古巴");
        map.put("CZ", "捷克");
        map.put("CY", "塞浦路斯");
        map.put("DK", "丹麦");
        map.put("DJ", "吉布提");
        map.put("DO", "多米尼加代表");
        map.put("DO", "多米尼加");
        map.put("EC", "厄瓜多尔");
        map.put("EG", "埃及");
        map.put("GQ", "赤道几内亚");
        map.put("ER", "厄立特里亚");
        map.put("EE", "爱沙尼亚");
        map.put("ET", "埃塞俄比亚");
        map.put("FO", "法罗是");
        map.put("FJ", "斐济");
        map.put("FI", "芬兰");
        map.put("FR", "法国");
        map.put("FX", "法国大都会");
        map.put("FK", "福克兰是");
        map.put("GF", "法属圭亚那");
        map.put("PF", "法属波利尼西亚");
        map.put("GA", "加蓬");
        map.put("GM", "冈比亚");
        map.put("GE", "格鲁吉亚");
        map.put("DE", "德国");
        map.put("GH", "加纳");
        map.put("GI", "直布罗陀");
        map.put("GR", "希腊");
        map.put("GD", "格林纳达");
        map.put("GP", "瓜德罗普岛是");
        map.put("GU", "关岛");
        map.put("GT", "危地马拉");
        map.put("GG", "根西岛");
        map.put("GW", "几内亚比绍");
        map.put("GN", "几内亚");
        map.put("GY", "圭亚那");
        map.put("GL", "格陵兰岛是");
        map.put("HT", "海地");
        map.put("HN", "宏都拉斯");
        map.put("HU", "匈牙利");
        map.put("IS", "冰岛");
        map.put("IN", "印度");
        map.put("ID", "印尼");
        map.put("IR", "伊朗");
        map.put("IQ", "伊拉克");
        map.put("IE", "爱尔兰");
        map.put("IM", "马恩岛");
        map.put("IL", "以色列");
        map.put("IT", "意大利");
        map.put("JM", "牙买加");
        map.put("JP", "日本");
        map.put("JE", "泽西岛");
        map.put("JO", "约旦");
        map.put("KZ", "哈萨克斯坦");
        map.put("KE", "肯尼亚");
        map.put("KI", "基里巴斯");
        map.put("KR", "韩国");
        map.put("KD", "朝鲜");
        map.put("KW", "科威特");
        map.put("KG", "吉尔吉斯斯坦");
        map.put("KY", "开曼群岛是");
        map.put("KN", "ST.CHRISTOPHER和尼维斯");
        map.put("LO", "老挝");
        map.put("LV", "拉脱维亚");
        map.put("LB", "黎巴嫩");
        map.put("LS", "莱索托");
        map.put("LR", "利比里亚");
        map.put("LY", "利比亚");
        map.put("LI", "列支敦斯登");
        map.put("LT", "立陶宛");
        map.put("LU", "卢森堡");
        map.put("MK", "马其顿");
        map.put("MW", "马拉维");
        map.put("MY", "马来西亚");
        map.put("MG", "马达加斯加");
        map.put("MV", "马尔代夫");
        map.put("ML", "马里");
        map.put("MT", "马耳他");
        map.put("MH", "马绍尔群岛");
        map.put("MQ", "马提尼克岛");
        map.put("MR", "毛利塔尼亚");
        map.put("MU", "毛里求斯");
        map.put("YT", "马约特");
        map.put("MX", "墨西哥");
        map.put("MF", "密克罗尼西亚");
        map.put("MD", "摩尔多瓦");
        map.put("MC", "摩纳哥");
        map.put("MN", "蒙古");
        map.put("ME", "黑山");
        map.put("MS", "蒙特塞拉特岛是");
        map.put("MA", "摩洛哥");
        map.put("MZ", "莫桑比克");
        map.put("MM", "缅甸");
        map.put("NA", "纳米比亚");
        map.put("NR", "瑙鲁");
        map.put("NP", "尼泊尔");
        map.put("NL", "荷兰");
        map.put("NC", "新喀里多尼亚");
        map.put("NZ", "新西兰");
        map.put("NI", "尼加拉瓜");
        map.put("NE", "尼日尔");
        map.put("NG", "尼日利亚");
        map.put("NU", "纽埃岛是");
        map.put("NF", "诺福克岛");
        map.put("NO", "挪威");
        map.put("OM", "阿曼");
        map.put("PK", "巴基斯坦");
        map.put("PW", "帕劳");
        map.put("PS", "巴勒斯坦");
        map.put("PA", "巴拿马");
        map.put("PG", "巴布亚新几内亚");
        map.put("PE", "秘鲁");
        map.put("PH", "菲律宾");
        map.put("PN", "皮特凯恩群岛");
        map.put("PL", "波兰");
        map.put("PT", "葡萄牙");
        map.put("PR", "波多黎各");
        map.put("PY", "巴拉圭");
        map.put("PM", "圣皮埃尔和密克隆群岛");
        map.put("QA", "卡塔尔");
        map.put("RE", "留尼汪岛");
        map.put("RO", "罗马尼亚");
        map.put("RW", "卢旺达");
        map.put("RU", "俄罗斯");
        map.put("SH", "圣赫勒拿");
        map.put("LC", "圣卢西亚");
        map.put("VG", "圣文森特和格林纳丁斯");
        map.put("SV", "萨尔瓦多");
        map.put("SM", "圣马力诺");
        map.put("ST", "圣多美和普林西比");
        map.put("SA", "沙特阿拉伯");
        map.put("SN", "塞内加尔");
        map.put("SL", "塞拉利昂");
        map.put("SG", "新加坡");
        map.put("RS", "塞尔维亚");
        map.put("SK", "斯洛伐克语");
        map.put("SI", "斯洛文尼亚");
        map.put("SB", "所罗门群岛");
        map.put("SO", "索马里");
        map.put("ZA", "南非");
        map.put("ES", "西班牙");
        map.put("LK", "斯里兰卡");
        map.put("SD", "苏丹");
        map.put("SR", "苏里南");
        map.put("SZ", "斯威士兰");
        map.put("SE", "瑞典");
        map.put("CH", "瑞士");
        map.put("SY", "叙利亚");
        map.put("TJ", "塔吉克斯坦");
        map.put("TZ", "坦桑尼亚");
        map.put("TH", "泰国");
        map.put("TT", "特立尼达和多巴哥");
        map.put("TL", "东帝汶");
        map.put("TG", "多哥");
        map.put("TK", "托克劳是");
        map.put("TO", "汤加");
        map.put("TN", "突尼斯");
        map.put("TR", "土耳其");
        map.put("TM", "土库曼斯坦");
        map.put("TV", "图瓦卢");
        map.put("TC", "特克斯和凯科斯是");
        map.put("UG", "乌干达");
        map.put("UA", "乌克兰");
        map.put("AE", "阿联酋");
        map.put("UK", "英国");
        map.put("US", "美国");
        map.put("UY", "乌拉圭");
        map.put("UZ", "乌兹别克斯坦");
        map.put("VA", "梵蒂冈");
        map.put("VE", "委内瑞拉");
        map.put("VN", "越南");
        map.put("VU", "瓦努阿图");
        map.put("WF", "墙壁瓦利斯群岛和富图纳群岛");
        map.put("EH", "西撒哈拉");
        map.put("YE", "也门");
        map.put("YU", "南斯拉夫");
        map.put("ZM", "赞比亚");
        map.put("ZW", "津巴布韦");
        map.put("SC", "塞舌尔共和国");
        map.put("HK", "香港");
        map.put("MO", "澳门");
        map.put("TW", "台湾");

        List list = new ArrayList();
        list.add("南非");
        list.add("希腊");
        list.add("荷兰");
        list.add("比利时");
        list.add("法国");
        list.add("西班牙");
        list.add("匈牙利");
        list.add("意大利");
        list.add("罗马尼亚");
        list.add("瑞士");
        list.add("奥地利");
        list.add("英国");
        list.add("丹麦");
        list.add("瑞典");
        list.add("挪威");
        list.add("波兰");
        list.add("德国");
        list.add("秘鲁");
        list.add("墨西哥");
        list.add("古巴");
        list.add("阿根廷");
        list.add("巴西");
        list.add("智利");
        list.add("哥伦比亚");
        list.add("委内瑞拉");
        list.add("马来西亚");
        list.add("澳大利亚");
        list.add("印尼");
        list.add("菲律宾");
        list.add("新西兰");
        list.add("新加坡");
        list.add("泰国");
        list.add("日本");
        list.add("韩国");
        list.add("越南");
        list.add("土耳其");
        list.add("印度");
        list.add("巴基斯坦");
        list.add("阿富汗");
        list.add("斯里兰卡");
        list.add("缅甸");
        list.add("伊朗");
        list.add("摩洛哥");
        list.add("阿尔及利亚");
        list.add("突尼斯");
        list.add("利比亚");
        list.add("冈比亚");
        list.add("塞内加尔");
        list.add("毛利塔尼亚");
        list.add("马里");
        list.add("几内亚");
        list.add("象牙海岸");
        list.add("布基纳法索");
        list.add("尼日尔");
        list.add("多哥");
        list.add("贝宁");
        list.add("毛里求斯");
        list.add("利比里亚");
        list.add("塞拉利昂");
        list.add("加纳");
        list.add("尼日利亚");
        list.add("乍得");
        list.add("非洲中部");
        list.add("喀麦隆");
        list.add("佛得角");
        list.add("圣多美和普林西比");
        list.add("赤道几内亚");
        list.add("加蓬");
        list.add("刚果");
        list.add("刚果(金)");
        list.add("安哥拉");
        list.add("几内亚比绍");
        list.add("迪戈加西亚岛");
        list.add("提升");
        list.add("塞舌尔共和国");
        list.add("苏丹");
        list.add("卢旺达");
        list.add("埃塞俄比亚");
        list.add("索马里");
        list.add("吉布提");
        list.add("肯尼亚");
        list.add("坦桑尼亚");
        list.add("乌干达");
        list.add("布隆迪");
        list.add("莫桑比克");
        list.add("桑给巴尔岛");
        list.add("赞比亚");
        list.add("马达加斯加");
        list.add("聚会是");
        list.add("津巴布韦");
        list.add("纳米比亚");
        list.add("马拉维");
        list.add("莱索托");
        list.add("博茨瓦纳");
        list.add("斯威士兰");
        list.add("科摩罗");
        list.add("ST.HELENA");
        list.add("厄立特里亚");
        list.add("法罗是");
        list.add("格陵兰岛是");
        list.add("直布罗陀");
        list.add("葡萄牙");
        list.add("卢森堡");
        list.add("爱尔兰");
        list.add("冰岛");
        list.add("阿尔巴尼亚");
        list.add("马耳他");
        list.add("塞浦路斯");
        list.add("芬兰");
        list.add("保加利亚");
        list.add("立陶宛");
        list.add("拉脱维亚");
        list.add("爱沙尼亚");
        list.add("摩尔多瓦");
        list.add("亚美尼亚");
        list.add("白俄罗斯");
        list.add("安道尔");
        list.add("摩纳哥");
        list.add("圣马力诺");
        list.add("乌克兰");
        list.add("南斯拉夫");
        list.add("克罗地亚");
        list.add("斯洛文尼亚");
        list.add("波黑");
        list.add("马其顿");
        list.add("捷克");
        list.add("斯洛伐克语");
        list.add("福克兰是");
        list.add("伯利兹");
        list.add("GUATEMAILA");
        list.add("萨尔瓦多");
        list.add("宏都拉斯");
        list.add("尼加拉瓜");
        list.add("哥斯达黎加");
        list.add("巴拿马");
        list.add("圣皮埃尔和密克隆群岛");
        list.add("海地");
        list.add("瓜德罗普岛是");
        list.add("玻利维亚");
        list.add("GUYANY");
        list.add("厄瓜多尔");
        list.add("法属圭亚那");
        list.add("巴拉圭");
        list.add("马提尼克岛");
        list.add("苏里南");
        list.add("乌拉圭");
        list.add("诺福克是");
        list.add("文莱");
        list.add("瑙鲁");
        list.add("巴布亚新几内亚");
        list.add("汤加");
        list.add("所罗门群岛");
        list.add("瓦努阿图");
        list.add("斐济");
        list.add("帕劳");
        list.add("库克是");
        list.add("纽埃岛是");
        list.add("萨摩亚、东部");
        list.add("萨摩亚,西方");
        list.add("基里巴斯");
        list.add("图瓦卢");
        list.add("法属波利尼西亚");
        list.add("托克劳是");
        list.add("密克罗尼西亚");
        list.add("马歇尔是");
        list.add("韩国");
        list.add("香港");
        list.add("澳门");
        list.add("柬埔寨");
        list.add("老挝");
        list.add("孟加拉国");
        list.add("台湾");
        list.add("马尔代夫");
        list.add("黎巴嫩");
        list.add("约旦");
        list.add("叙利亚");
        list.add("伊拉克");
        list.add("科威特");
        list.add("沙特阿拉伯");
        list.add("也门");
        list.add("阿曼");
        list.add("阿联酋");
        list.add("以色列");
        list.add("巴林");
        list.add("卡塔尔");
        list.add("不丹");
        list.add("蒙古");
        list.add("尼泊尔");
        list.add("土库曼斯坦");
        list.add("阿塞拜疆");
        list.add("乔治亚州");
        list.add("吉尔吉斯斯坦");
        list.add("乌兹别克斯坦");
        list.add("巴哈马群岛");
        list.add("巴巴多斯");
        list.add("ANGULLIA IS");
        list.add("安提瓜岛和巴布达");
        list.add("维珍群岛（英属）");
        list.add("维珍群岛(美属)");
        list.add("开曼群岛是");
        list.add("百慕大群岛是");
        list.add("格林纳达");
        list.add("特克斯和凯科斯是");
        list.add("蒙特塞拉特岛是");
        list.add("马里亚纳是");
        list.add("关岛");
        list.add("墙壁瓦利斯群岛和富图纳群岛");
        list.add("多米尼加");
        list.add("圣卢西亚");
        list.add("波多黎各");
        list.add("后是");
        list.add("多米尼加代表");
        list.add("特立尼达和多巴哥");
        list.add("ST.CHRISTOPHER和尼维斯");
        list.add("牙买加");
        list.add("列支敦斯登");
        list.add("中国");
        list.add("美国加拿大");
        list.add("俄罗斯");
        list.add("埃及");


        System.out.println("Map<String, String> map = new HashMap();");
        List noHasCountry = new ArrayList();
        List noHasCountry2 = new ArrayList();
        boolean isHas = false;
        boolean isHas2 = false;
        for (Map.Entry entry : map.entrySet()) {

            System.out.println("map.put(\"" + entry.getValue() + "\",\"" + entry.getKey() + "\");");
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).equals(entry.getValue())) {
                    isHas2 = true;
                    break;
                }
            }
            if (!isHas2) {
                noHasCountry2.add(entry.getValue());
            }
            isHas2 = false;
        }
        for (int j = 0; j < list.size(); j++) {
            for (Map.Entry entry : map.entrySet()) {
                if (list.get(j).equals(entry.getValue())) {
                    isHas = true;
                    break;
                }
            }
            if (!isHas) {
                noHasCountry.add(list.get(j));
            }
            isHas = false;
        }

        System.out.println("---------------------------------------");
        for (int i = 0; i < noHasCountry.size(); i++) {
            System.out.print("'" + noHasCountry.get(i) + "',");
        }
        System.out.println("");
        System.out.println("---------------------------------------");
        for (int i = 0; i < noHasCountry2.size(); i++) {
            System.out.print("'" + noHasCountry2.get(i) + "',");
        }
    }
}
